### ISSUE TITLE
Compile under Linux with gcc 4.9.1

### ISSUE THREAD

**Issue by saemideluxe** [vcosta/derclou#1]
Hi

I tried to compile the project under Linux with gcc. I had to adjust something. If this project is still maintained, let me now when I should make a pull request. Btw. is there some relation to the project on SourceForce? They are recently very active but do not provide any build files which lead me to trouble while compiling.

Regards
Sam

**Comment by vcosta** [comment]
Sure either do that or send me a patch file generated with 'diff -u'.

This project has no relation with the one on SourceForge. Different team. I
originally started this project because none of the existing projects, back
then, worked under Linux properly. I think they use some code of mine and I
use some code by other people. All of us started from the same source code
release by NEO Software GmbH, which was the game developer, but the trees
diverged.

I haven't had the time to work on this for a while. The UI code needs
debugging. The mouse handling needs debugging. The game should work fine
with the keyboard but I haven't done a full playthrough to be sure.

On Wed, Feb 18, 2015 at 7:36 PM, samuelvonstachelski <
notifications@github.com> wrote:

> Hi
> 
> I tried to compile the project under Linux with gcc. I had to adjust
> something. If this project is still maintained, let me now when I should
> make a pull request. Btw. is there some relation to the project on
> SourceForce? They are recently very active but do not provide any build
> files which lead me to trouble while compiling.
> 
> Regards
> Sam
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vcosta/derclou/issues/1.

## 

Vasco Alexandre da Silva Costa
PhD Student at Department of Information Systems and Computer Science
IST/Technical University of Lisbon

**Comment by vcosta** [comment]
Tested and compiles with latest GCC version.
